## Tensors are similar to NumPy’s ndarrays, except that tensors can run on GPUs or other specialized hardware to accelerate computing.

In [1]:
import numpy as np
import torch

In [2]:
# List to Tensor
data = [[1,2], [3,4]]
x_data = torch.tensor(data)

"""
Example:
list_ = [1,2,3,4]
list_tensor = torch.tensor(list_)
"""

'\nExample:\nlist_ = [1,2,3,4]\nlist_tensor = torch.tensor(list_)\n'

In [3]:
x_data ## __repr__ -> tensor([data])

tensor([[1, 2],
        [3, 4]])

In [4]:
# Numpy to Tensor
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

"""
Example:
list_ = np.array([1,2,3,4])
list_tensor = torch.from_numpy(list_)
"""

'\nExample:\nlist_ = np.array([1,2,3,4])\nlist_tensor = torch.from_numpy(list_)\n'

In [5]:
x_np

tensor([[1, 2],
        [3, 4]])

In [6]:
# The new tensor retains the properties (shape, datatype) of the argument tensor, unless explicitly overridden.

x_ones = torch.ones_like(x_data) # retains the properties of x_data and it creates a tensor which elements are consist of one(s)
print(f"Ones Tensor: \n {x_ones} \n")
print(x_data)

x_ones = torch.zeros_like(x_data) # retains the properties of x_data and it creates a tensor which elements are consist of one(s)
print(f"\nZeros Tensor: \n {x_ones} \n")
print(x_data)

x_rand = torch.rand_like(x_data, dtype=torch.float) # retains the properties of x_data, it creates a tensor which elements are consist of rand(s)
print(f"\nRandom Tensor: \n {x_rand} \n")
print(x_np)

"""
Example:
b = torch.tensor([[3,4,5],[5,6,7]])
b_torch_random = torch.rand_like(b, dtype = torch.float)
"""

## in addition, if data type not written. It uses the original(x_data)'s dtype and also the device of original data such if we selech device as cuda. x_rand's device will be CUDA.

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

tensor([[1, 2],
        [3, 4]])

Zeros Tensor: 
 tensor([[0, 0],
        [0, 0]]) 

tensor([[1, 2],
        [3, 4]])

Random Tensor: 
 tensor([[0.4842, 0.2953],
        [0.2105, 0.6242]]) 

tensor([[1, 2],
        [3, 4]])


'\nExample:\nb = torch.tensor([[3,4,5],[5,6,7]])\nb_torch_random = torch.rand_like(b, dtype = torch.float)\n'

In [7]:
shape = (2,3) # in 1D arrays we must put comma at the end of tuple to understand whether it is a tuple or not.
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [8]:
print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.4555, 0.1968, 0.3553],
        [0.0407, 0.6508, 0.3726]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Tensor Attributes

In [9]:
tensor = torch.rand((2,2))

print(f"Shape of tensor: {tensor.shape}\n") # [2,2] first is row, second is column
print(f"Datatype of tensor: {tensor.dtype}\n") # int64, float32, etc.
print(f"Device tensor is stored on: {tensor.device}") # Cpu or Cuda

Shape of tensor: torch.Size([2, 2])

Datatype of tensor: torch.float32

Device tensor is stored on: cpu


## Tensor Operations:

In [10]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Device tensor is stored on: {device}")

Device tensor is stored on: cpu


In [11]:
# Slicing:

# Access the first element
x_1d = torch.tensor([10,11,12,13,14])
x_1d[0]

# Acces the last element
x_1d[-1]

# Modify an element
x_1d[2] = 20

In [12]:
x_1d[2]

tensor(20)

In [13]:
# Create a 2D tensor

x_2d = torch.rand((4,4))

print(x_2d)
print("\n")

# Access the element at row 1, column 2
print(x_2d[0,1])
print("\n")

# Access the entire second column (index 1)
print(x_2d[:,1])
print("\n")

# Modify an element
x_2d[1,1] = 2
print(x_2d)
print("\n")

# Select the first two rows and columns 1 and 2
print(x_2d[0:2, 1:3])
print("\n")

# Select all rows, but only the last two columns
print(x_2d[:, -2:])
print("\n")

tensor([[0.3860, 0.0875, 0.3490, 0.8514],
        [0.1729, 0.9350, 0.9715, 0.2994],
        [0.3643, 0.9743, 0.5814, 0.1954],
        [0.5270, 0.1764, 0.6478, 0.2652]])


tensor(0.0875)


tensor([0.0875, 0.9350, 0.9743, 0.1764])


tensor([[0.3860, 0.0875, 0.3490, 0.8514],
        [0.1729, 2.0000, 0.9715, 0.2994],
        [0.3643, 0.9743, 0.5814, 0.1954],
        [0.5270, 0.1764, 0.6478, 0.2652]])


tensor([[0.0875, 0.3490],
        [2.0000, 0.9715]])


tensor([[0.3490, 0.8514],
        [0.9715, 0.2994],
        [0.5814, 0.1954],
        [0.6478, 0.2652]])




In [14]:
# Concatenate

t = torch.rand((4,4))
print(t)

tensor([[0.7160, 0.8256, 0.6970, 0.3038],
        [0.3008, 0.2961, 0.9621, 0.0972],
        [0.4960, 0.7900, 0.6178, 0.2900],
        [0.5909, 0.0954, 0.6496, 0.6302]])


In [15]:
t1 = torch.cat([t,t,t], dim = 0) # concatenate a sequence of tensors along a given dimension

In [16]:
t1

tensor([[0.7160, 0.8256, 0.6970, 0.3038],
        [0.3008, 0.2961, 0.9621, 0.0972],
        [0.4960, 0.7900, 0.6178, 0.2900],
        [0.5909, 0.0954, 0.6496, 0.6302],
        [0.7160, 0.8256, 0.6970, 0.3038],
        [0.3008, 0.2961, 0.9621, 0.0972],
        [0.4960, 0.7900, 0.6178, 0.2900],
        [0.5909, 0.0954, 0.6496, 0.6302],
        [0.7160, 0.8256, 0.6970, 0.3038],
        [0.3008, 0.2961, 0.9621, 0.0972],
        [0.4960, 0.7900, 0.6178, 0.2900],
        [0.5909, 0.0954, 0.6496, 0.6302]])

In [17]:
# Stack: Concatenates a sequence of tensors along a new dimension.

x = torch.randn(2, 3)
x
torch.stack((x, x), dim=1)



tensor([[[ 1.6520, -0.8549,  0.1564],
         [ 1.6520, -0.8549,  0.1564]],

        [[ 1.4182,  0.9583, -0.7250],
         [ 1.4182,  0.9583, -0.7250]]])

In [18]:
# This computes the element-wise product
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
# Alternative syntax:
print(f"tensor * tensor \n {tensor * tensor}")

tensor.mul(tensor) 
 tensor([[4.7267e-04, 3.2020e-01],
        [6.4842e-01, 7.1960e-02]]) 

tensor * tensor 
 tensor([[4.7267e-04, 3.2020e-01],
        [6.4842e-01, 7.1960e-02]])


In [19]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
# Alternative syntax:
print(f"tensor @ tensor.T \n {tensor @ tensor.T}")

tensor.matmul(tensor.T) 
 tensor([[0.3207, 0.1693],
        [0.1693, 0.7204]]) 

tensor @ tensor.T 
 tensor([[0.3207, 0.1693],
        [0.1693, 0.7204]])


## Shape Manipulation

Let's continue with shape manipulation, specifically view vs reshape. The main deal is: view uses the exact same data directly, while reshape creates a brand new copy if it has to.

This all comes down to the logic of 'contiguity'. If the data in the tensor is lined up perfectly back-to-back in the memory (RAM), we can easily grab it using view. But if there are weird, random gaps in the memory layout, we can't do that.

For example, if we try to grab the 3rd and 5th columns, the data isn't sitting together—it's jumping around in the memory. Since it's not contiguous anymore, view fails, and we are forced to use reshape so it can create a fresh, straight copy of that data under the hood

In [25]:
# view, reshape


v_tensor = torch.arange(12)
print(v_tensor)

a = v_tensor.view((3,4))
print(a)

# to make flatten -1 must be written such that:

flatten_shape = a.view(-1)
print(flatten_shape)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [26]:
# Inplace method: Direct change the memory element. Do not create any copy.

t2 = torch.tensor([1,2,3])
t2.add_(5) # _ -> generally, use for in-place methods.
print(t2)

tensor([6, 7, 8])


## Broadcasting

In [ ]:
"""
Broadcastins works when dimensions match or one of the dimensions is 1

-> Numpy compares shapes from right to left.
-> If they are compatible, it automatically expands the smaller one.

:::
Firstly, we are trying to sum those two vectors.
[256, 256, 1]
[1]

But the dimensions are not matched. Broadcasting!!!

Torch fill the blank dimensionsion with 1 if right to the left comparison is successful.

[256, 256, 1]
-> [1, 1 ,1] (new second vector.)

-> then it extend ones to 256 by comparing one by one

x-dimension: 1 - 1 (Same, Skip)
y-dimension: 256 - 1 (Not same extend 1 to 256)
z-dimension: 256 - 1 (Not same extend 1 to 256)

[256, 256, 1]
[256, 256, 1] will be the last output.

A tensor:  [4, 1]
B tensor:  [1, 3]
------------------
Comparison:
1st Dimension: 1 and 3, 1 of A's tensor will be extended to 3.
2nd Dimension: 4 ve 1, 1 of B's tensor will be extended to 4.

A: [4,3].
B: [4,3].

"""